/* eslint-disable no-console */
/* eslint-disable react/jsx-no-bind */
import Head from 'next/head';
import Button from '../components/Button';

export default function Home() {
  function handleClick() {
    console.log('Liked the page!');
  }

  return (
    <>
      <Head>
        <title>Nextjs Fortress</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Nextjs Fortress</h1>

      <Button handleClick={handleClick} title="logIn" />
      <Button handleClick={handleClick} title="signup" />
    </>
  );
}
